name: Application Workflow

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      BUNDLE_WITHOUT: "development:production"
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rails db:prepare
          bundle exec rails test

  deliver:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: test
    runs-on: ubuntu-20.04
    outputs:
      lowercase-repository-name: ${{ steps.change-string-case.outputs.lowercase }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Convert repository name to lowercase
        id: change-string-case
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ghcr.io/${{ steps.change-string-case.outputs.lowercase }}/app:2.0.${{ github.run_number }}
            ghcr.io/${{ steps.change-string-case.outputs.lowercase }}/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: deliver
    runs-on: ubuntu-20.04
    env:
      LOWERCASE_REPOSITORY_NAME: ${{ needs.deliver.outputs.lowercase-repository-name }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      HOSTNAME: ${{ secrets.HOSTNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          envs: |
            LOWERCASE_REPOSITORY_NAME
            RAILS_MASTER_KEY
            HOSTNAME
            DB_NAME
            DB_HOST
            DB_PORT
            DB_USERNAME
            DB_PASSWORD
            GITHUB_RUN_NUMBER
          script: |
            docker stop bookshelf
            docker rm bookshelf
            docker run -d --name bookshelf --restart unless-stopped -p 3000:3000 \
              -e RAILS_MASTER_KEY="$RAILS_MASTER_KEY" \
              -e HOSTNAME="$HOSTNAME" \
              -e DB_NAME="$DB_NAME" \
              -e DB_HOST="$DB_HOST" \
              -e DB_PORT="$DB_PORT" \
              -e DB_USERNAME="$DB_USERNAME" \
              -e DB_PASSWORD="$DB_PASSWORD" \
              "ghcr.io/$LOWERCASE_REPOSITORY_NAME/app:2.0.$GITHUB_RUN_NUMBER"
